name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Print swift version
      run: swift --version
    - name: Run tests
      run: ./test.sh
